import { Router } from 'express';
import authRoutes from './auth.routes.js';
import employeeRoutes from './employee.routes.js';
import officeRoutes from './office.routes.js';
import departmentRoutes from './department.routes.js';
import teamRoutes from './team.routes.js';
import attendanceRoutes from './attendance.routes.js';
import holidayRoutes from './holiday.routes.js';
import leaveRoutes from './leave.routes.js';
import notificationRoutes from './notification.routes.js';
import taskRoutes from './task.routes.js';
import goalRoutes from './goal.routes.js';
import performanceRoutes from './performance.routes.js';
import announcementRoutes from './announcement.routes.js';
import recognitionRoutes from './recognition.routes.js';
import messageRoutes from './message.routes.js';
import analyticsRoutes from './analytics.routes.js';
import floorRoutes from './floor.routes.js';
import deskRoutes from './desk.routes.js';
import workforceRoutes from './workforce.routes.js';
import reportRoutes from './report.routes.js';

const router = Router();

router.use('/auth', authRoutes);
router.use('/employees', employeeRoutes);
router.use('/offices', officeRoutes);
router.use('/departments', departmentRoutes);
router.use('/teams', teamRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/holidays', holidayRoutes);
router.use('/leaves', leaveRoutes);
router.use('/notifications', notificationRoutes);
router.use('/tasks', taskRoutes);
router.use('/goals', goalRoutes);
router.use('/performance', performanceRoutes);
router.use('/announcements', announcementRoutes);
router.use('/recognitions', recognitionRoutes);
router.use('/messages', messageRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/floors', floorRoutes);
router.use('/desks', deskRoutes);
router.use('/workforce', workforceRoutes);
router.use('/reports', reportRoutes);

export default router;
